Capstone/librarian/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('librarian/', views.main, name='librarian'),
    path('librarian/delete_book/<int:book_id>/', views.delete_book, name='delete_book'),
    path('librarian/delete_all_books/', views.delete_all_books, name='delete_all_books'),
    path('librarian/recently_deleted_books/delete_all/', views.delete_all_recently_deleted_books, name='delete_all_recently_deleted_books'),
    path('restore/<int:book_id>/', views.restore_book, name='restore_book'),
    path('toggle_availability/<int:book_id>/', views.toggle_availability, name='toggle_availability'),
    ##path('upload/', views.upload_view, name='upload_view'),
    path('borrow_requests/approve/<int:request_id>/', views.approve_request, name='approve_request'),
    path('borrow_requests/decline/<int:request_id>/', views.decline_request, name='decline_request'),
    path('delete_approved_request/<int:request_id>/', views.delete_approved_request, name='delete_approved_request'),
    path('delete_declined_request/<int:request_id>/', views.delete_declined_request, name='delete_declined_request'),
    path('librarian/', views.go_back, name='go_back'),
    path('delete_recently_deleted_books/<int:book_id>/', views.delete_recently_deleted_books, name='delete_recently_deleted_books'),
    path('toggle_book_status/<int:request_id>/', views.toggle_book_status, name='toggle_book_status'),
    path('book_status/', views.book_status_view, name='book_status_view'),
    path('toggle_out_status/<int:out_id>/', views.toggle_out_status, name='toggle_out_status'),
    path('edit_book/<int:book_id>/', views.edit_book, name='edit_book'),
    path('reset_filters/', views.reset_filters, name='reset_filters'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Capstone/storefront/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include('student.urls') ),
    path('librarian/',include('librarian.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('userauth/',include('userauth.urls')),
    path('adminside/',include('adminside.urls')),
    path('stud_app/',include('stud_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


    

Capstone/student/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('student/', views.student, name="view"),
    path('preview/<int:book_id>/', views.prev_file, name='prev_file'),
    path('book-detail/<int:book_id>/', views.book_detail, name='book_detail'),
    path('search_suggestions/', views.search_suggestions, name='search_suggestions'),
    path('bookmark/', views.bookmark, name='bookmark'),
    path('bookmark_toggle/', views.bookmark_toggle, name='bookmark_toggle'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('author/<str:author_name>/', views.author_detail, name='author_detail'),
    path('date/<int:publication_date>/', views.date_detail, name='date_detail'),
    path('list/<int:year>/', views.list, name='list'),
    path('author_list/', views.author_list, name='author_list'),
    path('author_detail/<str:author_name>/', views.author_detail, name='author_detail'),
    path('date/', views.date_list, name='date_list'),
    path('borrow-request/<int:book_id>/', views.borrow_request, name='borrow_request'),
    path('student/book-detail/<int:book_id>/', views.book_detail, name='book_detail'),
    path('request-history/', views.request_history_view, name='request_history'),
    path('bookmark_status/<int:book_id>/', views.bookmark_status, name='bookmark_status'),
    path('unbookmark_all/', views.unbookmark_all, name='unbookmark_all'),
    path('notifications/', views.fetch_notifications, name='fetch_notifications'),
    path('notifications/read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/delete/<int:notification_id>/', views.delete_notification, name='delete_notification'),
 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Capstone/librarian/models.py
import os
from django.db import models
from django.utils import timezone
from datetime import timedelta
# Create your models here.

from django.db import models
#from userauth.models import Account  # Import your custom Account model
from django.contrib.auth.models import User

from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from student.models import Notification
from django.db.models.signals import post_save
from django.utils.timezone import now
# Create your models here.



LANGUAGE_CHOICES = [
    ('english', 'English'),
    ('filipino', 'Filipino'),
    ('spanish', 'Spanish'),
    ('other', 'Other'),
]

class Category(models.Model):
    name = models.CharField(max_length=100, default="Def")
    code = models.CharField(max_length=100, default="")
    
    def __str__(self):
        return self.name

class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="Def")
    code = models.CharField(max_length=100, default="")
    def __str__(self):
        return  self.code + '-' + self.name

class Books(models.Model):
    BookTitle = models.CharField(max_length=100)
    Author = models.CharField(max_length=100)
    Description = models.TextField(null=True, blank=True)
    Date = models.DateField()
    Category = models.ManyToManyField(Category)
    SubCategory = models.ManyToManyField(SubCategory)
    Language = models.CharField(max_length=100, choices=LANGUAGE_CHOICES, default='english')
    BookFile = models.FileField(upload_to="books/files/", default='default_value.pdf')
    BookImage = models.ImageField(upload_to="books/images/", default='default_image.jpg')
    deleted_at = models.DateTimeField(null=True, blank=True)
    available = models.BooleanField(default=True)
    bookmarked_by = models.ManyToManyField(User, related_name='bookmarks', blank=True)
    borrowed = models.ManyToManyField(User, related_name='borrow', blank="True")
    PageViews = models.IntegerField(default=0)
    eBook = models.BooleanField(default=False)
    research_paper = models.BooleanField(default=False)
    hardCopy = models.BooleanField(default=False)
    stock = models.IntegerField(default=0)
    TimesBorrow = models.IntegerField(default=0)

    def __str__(self):
        return self.BookTitle
    
    def get_file_type(self):
        if self.eBook:
            return 'eBook'
        elif self.research_paper:
            return 'Research Paper'
        return 'Unknown'
    

def default_expiry():
    return timezone.now() + timedelta(days=3)

class BorrowRequest(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    requested_by = models.ForeignKey(User, on_delete=models.CASCADE)
    requested_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(default=default_expiry)
    status = models.CharField(max_length=20, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Expired', 'Expired')], default='Pending')
    file_type = models.CharField(max_length=20, choices=[('eBook', 'eBook'), ('Research Paper', 'Research Paper')], default='eBook')
    
    def is_expired(self):
        return timezone.now() > self.expires_at
    
    


class ApprovedRequest(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    requested_by = models.ForeignKey(User, on_delete=models.CASCADE)
    requested_at = models.DateTimeField()
    approved_at = models.DateTimeField(auto_now_add=True)
    inOut = models.BooleanField(default=True)
    expireTime = models.DateTimeField(default=default_expiry)

    def __str__(self):
        return f"{self.book} approved for {self.requested_by}"


def three_days_from_now():
    return now() + timedelta(days=3)

class Out(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    approved_at = models.DateTimeField(auto_now_add=True)
    out = models.BooleanField(default=False)
    returnTime = models.DateTimeField(default=three_days_from_now)
    
    def __str__(self):
        return f"{self.book} status"
    
def book_returnlog_expiry():
    return now() + timedelta(days=30)    

class ReturnLog(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    returnLogTime = models.DateTimeField(auto_now_add=True)
    expiryLogTime = models.DateTimeField(default=book_returnlog_expiry)
    
    def __str__(self):
        return f"{self.book} status"
    
    
class DeclinedRequest(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    requested_by = models.ForeignKey(User, on_delete=models.CASCADE)
    requested_at = models.DateTimeField()
    declined_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.book} declined for {self.requested_by}"
    
@receiver(post_save, sender=ApprovedRequest)
def create_approved_notification(sender, instance, created, **kwargs):
    if created:
        Notification.objects.create(
            user=instance.requested_by,
            message=f"Your request for {instance.book.BookTitle} has been approved."
        )

@receiver(post_save, sender=DeclinedRequest)
def create_declined_notification(sender, instance, created, **kwargs):
    if created:
        Notification.objects.create(
            user=instance.requested_by,
            message=f"Your request for {instance.book.BookTitle} has been declined."
        )

Capstone/librarian/forms.py
from django import forms
from .models import Books


class BookForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = ['BookTitle', 'Author', 'Date', 'Language','Category','SubCategory', 'BookFile', 'BookImage', 'Description', 'eBook','research_paper', 'hardCopy', 'stock'] 

Capstone/librarian/templates/editbooks.html
{% load custom_tags2 %}


{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href={% static "playground/school_Logo.png" %}>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <!--search-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!--help-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!--ebook icon-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!--article icon-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!--research Paper-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!--Bookmark-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <!--Close-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <title>Edit Book</title>

    <style>
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: Arial, Helvetica, sans-serif;
        }
        .main-content {
            background-color: #fff;
            padding: 20px 50px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 850px;
            max-height: 100vh;
            margin: auto;
            z-index: 1;
            position: relative;
        }
        h1 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #333;
            text-align: center;
        }
        .form-group label {
            font-weight: bold;
        }
        .form-check-label {
            margin-left: 5px;
            font-weight: normal;
        }
        button[type="submit"] {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            color: #fff;
            background-color: #007bff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-top: 20px;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        a {
            display: block;
            text-align: center;
            margin-top: 10px;
            color: #007bff;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
        .checkbox{
            display: flex;
            justify-content: space-around;
            align-items: center;
        }
        .checkbox-text{
            display:flex;
            flex-direction: row-reverse;
            margin-top: 10px;
            border: 1px solid rgb(74, 128, 210); 
            border-radius: 10px;
            color: white;
            background-color: rgb(74, 128, 210);
            padding: 10px 30px 10px 10px;
            font-weight: bold;
            position: relative
        }
        .form-check-input{
            transform: translate(15px, 0px);
        }
        .form-group-bot{
            display: flex;
            flex-direction: column;
            justify-content: center;
            text-align: center;
        }
        .form-group-bot a{
            white-space: nowrap; 
            overflow: hidden; 
            text-overflow: ellipsis;
        }
        .title, .main-title{
            text-align: center;
            font-weight: bold;
            font-size: 1.1rem;
        }
        .main-title{
            font-size: 1.6rem;
        }
        .sub-text{
            font-size: 1rem;
        }
        #id_BookImage, #id_BookFile{
            margin-left: auto;
        }
        .main-container{
            background-image: url({% static '/BG2.jpg' %});
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
        }
        .blur {
            display: flex;
            position: absolute;
            z-index: 0;
            top: 0;
            left: 0;
            background-color: rgba(112, 112, 112, 0.349);
            width: 100%;
            height: 100%;
            backdrop-filter: blur(2px);
        }
    </style>
</head>
<body>
    <div class="main-container">
        <div class="blur">
        </div>
        <div class="main-content">
            <h1 class="main-title">Edit Book</h1>
            <form method="post" enctype="multipart/form-data" action="{% url 'librarian' %}">
                {% csrf_token %}
                <div class="row mb-3">
                    <div class="form-group col">
                        <label for="id_BookTitle"  class="title">Title:</label>
                        <input type="text" class="form-control" id="id_BookTitle" name="BookTitle" required value="{{form.BookTitle.value}}">
                    </div>
                    <div class="form-group col">
                        <label for="id_Author" class="title">Author:</label>
                        <input type="text" class="form-control" id="id_Author" name="Author" required value="{{ form.Author.value }}">
                    </div>
                </div>
                <div class="form-group mb-3">
                    <label for="id_Description" class="title">Description:</label>
                    <input type="text" class="form-control" id="id_Description" name="Description" required value="{{ form.Description.value }}">
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_Date" class="title">Date:</label>
                            <input type="date" class="form-control" id="id_Date" name="Date" value="{{ form.Date.value|date:'Y-m-d' }}" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_Category" class="title">Category:</label>
                            <select class="form-control" id="id_Category" name="Category" required>
                                <option value="">Select a category</option>
                                {% for category_value, category_label in form.Category.field.choices %}
                                    <option value="{{ category_value }}">{{ category_label }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_Subcategories" class="title">SubCategory:</label>
                            <select class="form-control" id="id_Subcategories" name="SubCategory" required>
                                <option value="{{ form.SubCategory.value }}">{{ form.SubCategory.label }}</option>
                                    <option value="">Select a subcategory</option>
                                {% for subcategory_value, subcategory_label in form.SubCategory.field.choices %}
                                    <option value="{{ subcategory_value }}">{{ subcategory_label }}</option>
                                {% endfor %}
                            </select>

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_stock" class="title">Stock:</label>
                            <input type="number" class="form-control" id="id_stock" name="stock" value="{{ form.stock.value }}">
                            
                        </div>
                    </div>
                </div>
                <div class="checkbox">
                    <div class="form-group">
                        <div class="checkbox-text">
                            <label for="id_eBook" class="no-margin title">Ebook:</label>
                            <input class="form-check-input" type="checkbox" id="id_eBook" name="eBook" {% if book.ebook %}checked{% endif %}>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox-text">
                            <label for="id_research_paper" class="no-margin title">Research Paper:</label>
                            <input class="form-check-input" type="checkbox" id="id_research_paper" name="research_paper" {% if book.research_paper %}checked{% endif %}>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox-text">
                            <label for="id_hardCopy" class="no-margin title">HardCopy:</label>
                            <input class="form-check-input" type="checkbox" id="id_hardCopy" name="hardCopy" {% if book.hardCopy %}checked{% endif %}>
                        </div>
                    </div>
                </div>
                <div class="form-group mb-3">
                    <label for="id_Language" class="title">Language:</label>
                    <select class="form-control" id="id_Language" name="Language" required>
                        <option value="">{{form.Language.value}}</option>
                            <option value="">Select a language</option>
                        {% for language_value, language_label in form.Language.field.choices %}
                            <option value="{{ language_value }}">{{ language_label }}</option>
                        {% endfor %}
                    </select>  
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <div class="form-group-bot">
                            <label for="id_BookFile" class="title">Book File (PDF):</label>
                            {{ form.BookFile }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group-bot">
                            <label for="id_BookImage" class="title">Book Image (JPG):</label>
                            {{ form.BookImage }}
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary title">Upload</button>
            </form>
            <a href="{% url 'go_back' %}" class="title">Cancel</a>
        </div>
    </div>
    
    <script>
        function toggleCheckboxes(id1, id2) {
            var checkbox1 = document.getElementById(id1);
            var checkbox2 = document.getElementById(id2);
            if (checkbox1.checked) {
                checkbox2.checked = false;
            }
        }
    </script>
</body>
</html>